---
title: "Module 3 Readings"
format: html
editor: visual
---

For this module, please read the websites linked below. Unless otherwise noted, these sites are provided by Alaska Department of Fish and Game.

GOA = Gulf of Alaska

BSAI = Bering Sea/Aleutian Islands

### Hagfish

-   [Species profile](https://www.adfg.alaska.gov/index.cfm?adfg=hagfish.main)

### Lampreys

-   [Wildlife notebook overview](https://www.adfg.alaska.gov/static/education/wns/lampreys.pdf)

-   [Arctic lamprey species profile](https://www.adfg.alaska.gov/index.cfm?adfg=arcticlamprey.main)

-   [Pacific lamprey species profile](https://www.adfg.alaska.gov/index.cfm?adfg=pacificlamprey.main)

-   [River lamprey species profile](https://www.adfg.alaska.gov/index.cfm?adfg=riverlamprey.main)

### Sharks & skates

-   [Salmon shark species profile](https://www.adfg.alaska.gov/index.cfm?adfg=salmonshark.main)

-   [Pacific spiny dogfish species info](https://www.fisheries.noaa.gov/species/pacific-spiny-dogfish) (NOAA Fisheries)

-   [Sleeper shark](https://en.wikipedia.org/wiki/Pacific_sleeper_shark) (wikipedia)

-   [Great white shark](https://www.fisheries.noaa.gov/species/white-shark) (NOAA Fisheries)

-   [Skates of Alaska](https://www.adfg.alaska.gov/index.cfm?adfg=wildlifenews.view_article&articles_id=514)

    #### Optional Fishery information (has details about abundance and landings)

    <div>

    -   [GOA shark fishery info](https://apps-afsc.fisheries.noaa.gov/refm/docs/2020/GOAshark.pdf)

    -   [BSAI shark fishery info](https://apps-afsc.fisheries.noaa.gov/Plan_Team/2022/GOAshark.pdf)

    -   [GOA skate fishery info](https://apps-afsc.fisheries.noaa.gov/Plan_Team/2023/GOAskate.pdf)

    -   [BSAI skate fishery info](https://apps-afsc.fisheries.noaa.gov/Plan_Team/2023/BSAIskate.pdf)

    </div>

### Harvested marine mammals

-   [FAQ](https://www.fisheries.noaa.gov/alaska/outreach-and-education/marine-mammal-parts-and-products-alaska) about marine mammal harvest (NOAA)

-   [co-management ](https://www.fisheries.noaa.gov/alaska/marine-mammal-protection/co-management-marine-mammals-alaska)of marine mammals (NOAA)

-   [Bowhead whale](https://www.fisheries.noaa.gov/species/bowhead-whale) species info (NOAA)

-   [Beluga](https://www.fisheries.noaa.gov/species/beluga-whale) species info (NOAA)

-   [Stellar sea lion](https://www.fisheries.noaa.gov/species/steller-sea-lion) species info (NOAA)

-   ice seals species info (NOAA)

    -   [Bearded seal](https://www.fisheries.noaa.gov/species/bearded-seal)

    -   [Harp seal](https://www.fisheries.noaa.gov/species/harp-seal)

    -   [Hooded seal](https://www.fisheries.noaa.gov/species/hooded-seal)

    -   [Ribbon seal](https://www.fisheries.noaa.gov/species/ribbon-seal)

    -   [Ringed seal](https://www.fisheries.noaa.gov/species/ringed-seal)

    -   [Spotted seal](https://www.fisheries.noaa.gov/species/spotted-seal)

-   [Harbor seal](https://www.fisheries.noaa.gov/species/harbor-seal) species info (NOAA)

-   [Northern fur seal](https://www.fisheries.noaa.gov/species/northern-fur-seal) species info (NOAA)

-   [Walrus](https://www.adfg.alaska.gov/index.cfm?adfg=walrus.printerfriendly) species profile
